### ISSUE TITLE
Provide u-boot, boot0, boot1. sys_config.bin and binaries

### ISSUE THREAD

**Issue by kallisti5** [NextThingCo/CHIP-u-boot#1]
Once things get closer to go-live, please be sure to provide "final" boot binaries somewhere. (packaging up the binary build tools is handy as well)

A good Allwinner example is the cubieboard 4:
https://github.com/cubieboard/CC-A80-binaries

Allwinner uses a lot of blobs which can be messy to deal with when projects only release sd card images.

**Comment by mripard** [comment]
We won't be using any of these files but mainline U-boot, that already comes packaged in all the major distributions.
