### ISSUE TITLE
compiler-gcc6.h no such file or directory

### ISSUE THREAD

**Issue by cbabil** [NextThingCo/CHIP-u-boot#10]
When I try build the u-boot-chip receipt through toaster it gives me the following error. 

rom /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h:80:
/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
In file included from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler.h:54:0,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/part_efi.h:16,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/part.h:180,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h:80:
/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
compilation terminated.
compilation terminated.
/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf:47: recipe for target 'include/autoconf.mk.dep' failed
make[2]: *** [include/autoconf.mk.dep] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf:72: recipe for target 'include/autoconf.mk' failed
make[2]: *** [include/autoconf.mk] Error 1
In file included from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler.h:54:0,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/byteorder/little_endian.h:12,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/arch/arm/include/asm/byteorder.h:29,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/compiler.h:125,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/image.h:19,
                 from /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/common.h:82:
/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
compilation terminated.
/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git/scripts/Makefile.autoconf:75: recipe for target 'spl/include/autoconf.mk' failed
make[2]: *** [spl/include/autoconf.mk] Error 1
make[1]: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/uboot.release'.  Stop.
make[1]: Leaving directory '/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/build'
Makefile:145: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
make: Leaving directory '/home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/git'
ERROR: Function failed: do_compile (log file is located at /home/builder/poky/build-toaster-2/tmp/work/chip-poky-linux-gnueabi/u-boot-chip/2015.07+gitAUTOINC+854d5fcc64-r0/temp/log.do_compile.7824)

This is being build through the meta-chip layer with the following code:

DEPENDS += "dtc-native"
PROVIDES += "u-boot"

UBOOT_VERSION ?= "2015.07"
PV = "${UBOOT_VERSION}+git${SRCPV}"

SRCREV ?= "854d5fcc641d8d8914c03a69d7172815d5b81a99"
BRANCH ?= "chip/stable"
SRC_URI = "git://github.com/NextThingCo/CHIP-u-boot.git;branch=${BRANCH}"
S = "${WORKDIR}/git"

do_compile_append() {
    install ${B}/spl/${SPL_BINARY} ${B}/${SPL_BINARY}
}

COMPATIBLE_MACHINE = "chip"

How can I fix this? It seems that u-boot-chip is missing the gcc6.h file. Thanks.

**Comment by soderstrom-rikard** [comment]
It looks like there are patches for this, or at least something very similar, read the following
https://github.com/linux-sunxi/meta-sunxi/pull/149

Cheerio
soderstrom

**Comment by mripard** [comment]
I just pushed a commit that fixes that (d12df00332c171c520)

Thanks!
Maxime

**Comment by msolters** [comment]
Unfortunately I am seeing the following for gcc6:

```
In file included from include/linux/compiler.h:54:0,
                 from include/linux/bitops.h:5,
                 from ./include/common.h:20:
include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc6.h: No such file or directory
 #include gcc_header(__GNUC__)
                              ^
compilation terminated.
```

Adding the following as `include/linux/compiler-gcc6.h` seems to have worked:

```
#ifndef __LINUX_COMPILER_H
#error "Please don't include <linux/compiler-gcc6.h> directly, include <linux/compiler.h> instead."
#endif

#define __used				__attribute__((__used__))
#define __must_check			__attribute__((warn_unused_result))
#define __compiler_offsetof(a, b)	__builtin_offsetof(a, b)

/* Mark functions as cold. gcc will assume any path leading to a call
   to them will be unlikely.  This means a lot of manual unlikely()s
   are unnecessary now for any paths leading to the usual suspects
   like BUG(), printk(), panic() etc. [but let's keep them for now for
   older compilers]

   Early snapshots of gcc 4.3 don't support this and we can't detect this
   in the preprocessor, but we can live with this because they're unreleased.
   Maketime probing would be overkill here.

   gcc also has a __attribute__((__hot__)) to move hot functions into
   a special section, but I don't see any sense in this right now in
   the kernel context */
#define __cold			__attribute__((__cold__))

#define __UNIQUE_ID(prefix) __PASTE(__PASTE(__UNIQUE_ID_, prefix), __COUNTER__)

#ifndef __CHECKER__
# define __compiletime_warning(message) __attribute__((warning(message)))
# define __compiletime_error(message) __attribute__((error(message)))
#endif /* __CHECKER__ */

/*
 * Mark a position in code as unreachable.  This can be used to
 * suppress control flow warnings after asm blocks that transfer
 * control elsewhere.
 *
 * Early snapshots of gcc 4.5 don't support this and we can't detect
 * this in the preprocessor, but we can live with this because they're
 * unreleased.  Really, we need to have autoconf for the kernel.
 */
#define unreachable() __builtin_unreachable()

/* Mark a function definition as prohibited from being cloned. */
#define __noclone	__attribute__((__noclone__))

/*
 * Tell the optimizer that something else uses this function or variable.
 */
#define __visible __attribute__((externally_visible))

/*
 * GCC 'asm goto' miscompiles certain code sequences:
 *
 *   http://gcc.gnu.org/bugzilla/show_bug.cgi?id=58670
 *
 * Work it around via a compiler barrier quirk suggested by Jakub Jelinek.
 *
 * (asm goto is automatically volatile - the naming reflects this.)
 */
#define asm_volatile_goto(x...)	do { asm goto(x); asm (""); } while (0)

#ifdef CONFIG_ARCH_USE_BUILTIN_BSWAP
#define __HAVE_BUILTIN_BSWAP32__
#define __HAVE_BUILTIN_BSWAP64__
#define __HAVE_BUILTIN_BSWAP16__
#endif /* CONFIG_ARCH_USE_BUILTIN_BSWAP */
```

**Comment by agherzan** [comment]
Is this going to be in stable branch soon?
